bot name:
    cargo build \
        -p bot-{{ name }} \
        --release \
        --target riscv64-kartoffel-bot.json \
        --target-dir target.bots \
        -Z build-std \
        -Z build-std-features=compiler-builtins-mem
