bot name:
    cargo build \
        -p bot-{{ name }} \
        --release \
        --target riscv64-kartoffel-bot.json \
        --target-dir target.riscv \
        -Z build-std=alloc,core \
        -Z build-std-features=compiler-builtins-mem

bots:
    just bot chl-acyclic-maze
    just bot chl-flight-syndrome-enemy
    just bot dummy
    just bot roberto
